[[Poppler]]
arch = "aarch64"
git-tree-sha1 = "6a207c8e3b2defe789085c5c2bb2265b89f4b260"
os = "macos"

    [[Poppler.download]]
    sha256 = "d2f3fa022090aa95340cc616033c988df9a203464461a1cf4e5e592cc953b8cf"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.aarch64-apple-darwin.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a89ce10b56aee4a0713a8ab9ed733f483718d6c2"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "9a012010d233f8d40692526e263d66cb480c6711a5e0ec03015de79f7060c74b"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71b875f5d7402da301a28636636ae0b2163555bc"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "9ada8afe07e75c2614a4d0969b0404e254215a8bff8af8a433166b1d14e3ea09"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.aarch64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dd8f46dff319bcd5d55dce8c1378fe7b08360ad"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "e79dd25d2d2f19681c415ad71ca1b9f9143d606bd52b91e1045029153c6b6417"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38855954d1ff4137d55dc85996df2f2440aa5779"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "e0656b6fb122da08d318b9ac4bc89881a659b7c0e6a8524ef80fef7e6cc1a290"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaf213a228f3aa7678bfcf4fb567d28fe50efb70"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "6817204f0c8d7f56d6c824540d07b472e2b6089380591767f509d97f92d07e0f"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.i686-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4f1ccb304384feec02b71cacc028c295df00220"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "be09ccddf9c7f6b2d6f628de29c89254ff3d88b19d0aa9708edd2b230d64b036"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.i686-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ed1b21cfcc6b41421e765fbeb55caa82d05ca8b"
os = "windows"

    [[Poppler.download]]
    sha256 = "f9b612c30977450750a34259372b2da8e5d43857da30dc60b1d1e985b15700cc"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.i686-w64-mingw32-cxx11.tar.gz"
[[Poppler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaf2f5ba66f5fa7bc3cc71c32f00c0a9c5062709"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "afec881d8877e0bd63665b88544301c9a73f5cedf243ffaeee5667b6ea707ac7"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "a39c2cf620193e2c21fba7c685009925325bd700"
os = "macos"

    [[Poppler.download]]
    sha256 = "3125bdc5365cfe8a9eef2c4fc90a6fee6507fc40ccc8492fc921c3f7ef3d218c"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.x86_64-apple-darwin.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c26aa29d2df324fb8b22554ad29bf67e463a1155"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "5abd3edd49969d178c69bc89b3df664cfb97e06b75c9391494827383c84b6ee4"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc164b5056dd01daefa716b8abce90f635126bcd"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "d72415e3213aa1ecfea19081805f079ac2a7588230c2ae1ab7dc11fc2b7f51d6"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.x86_64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "c948be0515ea4f53c5f315ac0f4c05ae6bd622f8"
os = "freebsd"

    [[Poppler.download]]
    sha256 = "ae273a5af0410bbe84bc59a79a001f77542483d33e9cb3e318cf99517e22d152"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.x86_64-unknown-freebsd.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74dc21b191091e2e6c20bf067fb8c5b823239b7e"
os = "windows"

    [[Poppler.download]]
    sha256 = "f6f38e48bb73a1da88eba59ebc448dee9021f8224a964e8716ddd5c7c75cbc02"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v23.12.0+0/Poppler.v23.12.0.x86_64-w64-mingw32-cxx11.tar.gz"
