[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "052ea05235665db98964b49863b6000323b6fa93"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "a4dcbc780c70f62fcf1e1718f3b082bc701d6bf785a3f519290885f4cbe364e7"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e623d7549bade2ad406d1f110df3ceb8937faa8"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "d05239ce4bfd594418969e5a0c3ae8effb514a4d688dad53fe407f75de6461e1"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d963e1bf74bb1c6ea6ab1293b4178c40de085749"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "4d62a7012de2ea214847e79deca5e731ecbe36a2cfc6a30dc0d373bbfedcb92b"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.aarch64-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef695764dbf29e071e0680ea3f4aa7c7be6e6e44"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "33e7789e6ceeb068603e62e24d968300247891677dd76172d46d94b0378528ee"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.aarch64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46a10ea0feece33bc7f428831717cefd10cb864b"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "ff8f10072bba15d99836a29a3b814569b7fac1ce89058dc899d91281c822bc2c"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de2246794059f6b0f6dbe40fd6f1970ff0981cb3"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "1c434e3408368fa45dd0dce3c522aee75232054445b5e5662e405d87a1402824"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "590a981b3f0ea7207ebd9a62aca4fd6a2305c395"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "b86095386208720b3f694cbc6032d886c31be9aa8be8704cac6880940a72a9ca"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "252dcf710ec883346fd8ffcded6b10af7ff74396"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "d07e3e275ceaad9ff84795335bf363dd1196982628c1e51754e46edb49dae57d"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af9f3518c48f608a9cdf3e3f7b4347cd8017148a"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "b3e3fd678de5083dc2c71e38eb9b3570f48d6668a86727de0fc9b8c3ea833085"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.i686-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85239e26f2e36ac4a193c1eb96459dd22b74f291"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "45217eff364b5d1805b5f8df24fedfaa44ddd51368f0ae26b4d270a3bcbfa9fd"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.i686-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef0856a9b2ba18cf45168a1a34b67ebc45ae65ef"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "b04032f380b8c14219508619a267e40d1da0de2a4375c5159d18e5dec607d14f"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.i686-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c666b4f7ffa67c715fe5d67a4b632bd569dbc34a"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "85c37357412c1830f00cb107a8fd2567bc4935306166858505ee5222ed2b0d1a"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.i686-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef8c8279cd02b1d3bb071bc0011aa9109b588d7c"
os = "windows"

    [[Poppler.download]]
    sha256 = "d42a77599e6b37c313954b366464ce8039b9e88b95ee4f77d1376eb7e64d716b"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.i686-w64-mingw32-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7110813e6ef1fd9b56b11b9fa731f7f6edb3c363"
os = "windows"

    [[Poppler.download]]
    sha256 = "d0967fafb58fc7b0536fe18bc1b365fc30095d032128f59e840a136e7c5ae73d"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.i686-w64-mingw32-cxx11.tar.gz"
[[Poppler]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223738c78380aae41e071cabb1326d317602f8c9"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "3a9346587235b66c0997843612f94d4be7bc1a05b7e7fb3b6628bc1264d855c6"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30214e47e909b559aeb90eb7c5aad295accc493d"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "a513e3aa927791ac7331ed1384baba255ab7c005d691c781c28cc688a465b8eb"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "9a7dcb1f7a6c952c3cdfe98603f2a2081dfb8cf9"
os = "macos"

    [[Poppler.download]]
    sha256 = "e2b6c479d6a9c15c2f91dae8ae50f508cf6e8a5499e708359cb04ccc064684ae"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-apple-darwin.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c906d644e22a04919a03c0edcd889d56b35fa9c"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "36b39989e0f6c51f5c4e60907e2a59ae71c79c50e981c7e00c1c83c1f5a6430b"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c89139006ef6a48725584e152d2fb88877b7ff73"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "19ee2c6cd00a9f2e7b5e07e4b4951724a599f7e13c37515282f6fbef14fad448"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "157c69b945bcb0bad3c45ee2043d68ddc2e76102"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "1d1112094ddb656f311f4334215f504a348304e9db54bee39974b2f1c1cd7708"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c037a36f9de3ecb117415cf3429f18ee9dc5ff66"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "366a7a12dbaf1c67b87bca3abf727ca1ae0fb5f198fd0865b27ed75adc9b2dd5"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "bd80e17d41eeb039de100c88c1ae96751709cf1d"
os = "freebsd"

    [[Poppler.download]]
    sha256 = "8e2041e25420c91ceecba265a92e2a757e1d12dc011fbbfb69f850df726e4e36"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-unknown-freebsd.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9d477c2370624d1e4130e48ae5ea9d3a09ab954"
os = "windows"

    [[Poppler.download]]
    sha256 = "3e35a231c719d9686f1e1531c257dc15e2654cc72a1aef3e1dda42c165c18b82"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "214ca19a7884c0841fec919c9bc2121bdf404802"
os = "windows"

    [[Poppler.download]]
    sha256 = "8d75d476a20f871235a781f50ba55fb285799f0e9103cb8285cfba5b5a4ce525"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+2/Poppler.v0.87.0.x86_64-w64-mingw32-cxx11.tar.gz"
