[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2aa600f4103683a1ae3449aee7d645b29cb4d938"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "d54e951bc2dc9f0d5e0112f2391406dfd223d87222a0c0c3c612acfa2b72edb6"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc3332c6a44404230b3b6661da4e94284562bf57"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "eac15c565513a8c28538140e9b4cc2b35f058d0c1f6fdf20ca2d6f21b865f935"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f361e98aff7eec10726edbf6f67d575da669fd6"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "8c016b97c9c212429d7e679a1d5b71b3b9623c98e3ad897f30c426ed9d7b3543"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.aarch64-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8a4e570bc476f8b557856298fecd759cdeaa878"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "c4942f61b89fda78049de5433ac745f6940d18fdcb73d7f0e3ce0a74cf1e3b92"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.aarch64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f1293649fecacd61fa11d90abcbe654b2070273"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "7faaa7a27521b807ce58c74ce22ec5081384ee62acc50cd339fd42734a0f3768"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78c11a92b229c74d3e790c078d04eabe3aa4ffaa"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "cbc71017f18462b9d835f4228bad2a8f981564e2fbf34fd560dda4949d5e7ad5"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab7cf2cd640740f046f1cf3728e326bce7cdce82"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "cf5071c929e8a042651cf5be061d732b5e0388f23aa5136d32bf810be30f0f5f"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "487b466389ea3cc47831f3348c452183d8df60e3"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "03b0a9ecfba5c636dca59cb7e47dcc780906d764319656057479b1e0093c9b40"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "837572af2e4204162a3a5bb924cdf72863b74814"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "ca1dafe49be04b82eacee091925b1ff7fd77580ce87bbe3e0764c0846a15b004"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.i686-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bea5247da5feae96ed61684e35df915d3d13d0f"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "5423a58d356b81c2ffd6adc004184145f0454351992cdf18c835e11f8dbf025a"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.i686-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad748de7bfa4f01e77776f0f17fd77eacfdb82cb"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "5913a8274fb54e8883b371fdd8e4a6b6692b552c49d59c5964bf58a12b1b33b7"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.i686-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d0fc3b809982fe6f91ce1385ac4e94774cab69e"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "4510b81a7c2ed53699a1cea68fa343ac9a6ba36660847bbfa0fdc187fcd395f8"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.i686-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "294fb66d02021b2fae5651a7a0c0573af29c2023"
os = "windows"

    [[Poppler.download]]
    sha256 = "cdb18b71cd5c52031e2de95e06f90f77ccda038d265ea5ed4e6163b96a346d4d"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.i686-w64-mingw32-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9760f4c74790956082e4e0120ef072e91ba66df"
os = "windows"

    [[Poppler.download]]
    sha256 = "448e963e6e0492722d269886e8f8f89b4221f61f890f250557378f9ab39b2aa0"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.i686-w64-mingw32-cxx11.tar.gz"
[[Poppler]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2162d29ea72261c2925e70bb0026ffee220a7a2"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "53bca1cd1e0a128429db48a628dcad3ec133cfe5a80cc906a3176aef4474da53"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c500f0cdf2e2d21d31c663b13dcd468cd4cb3481"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "ec18b2ba943ed36e3e0efb04fe634be699e46755aa9b42c848c7f5120b2e4b14"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "271272d19a1a4567d20f05004b1b433869d4ed3c"
os = "macos"

    [[Poppler.download]]
    sha256 = "f59aa9a7805efbeb2b0069ed15f573e72ea23ba8f51aa6592b49b4849ecf6dfe"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-apple-darwin.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7e922eef9bc3228ce49e69e43ec341e053b1176"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "310558aba013e984ecb5679ab14132f6d71efdceb1cb64cd32761ebc6e2376e6"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6a277ec924c2c5d9c6d261d977886f3fcf2559f"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "dea6d2fe29e11501ee59da3da8ab5ae5be97596d9ba3a59e37c944bd0c8e6259"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d872ae3be1ed132a53f8589406d657f4fef2634b"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "7d8cbb04369852c87d5b0619b66a0f80ab54bb4e3f73fc078f33d02991aee0c5"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdffd087b7fc66c057cb68267df5e9b775f1ae73"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "4dbe9574fbe78e29d139c93a0de9dc232607febe96e0e5aef07c30bbab28a8da"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "1e31747e95f75c9d7c5b1c7a8096d916c6fc2826"
os = "freebsd"

    [[Poppler.download]]
    sha256 = "690765a34c00fa2e2ab9f34c3c78719ee6aafdbfeb7774d8c9ca4f26f9b52e0c"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-unknown-freebsd.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77354249cbfb671b7b5713ddf1da2279885bc5bf"
os = "windows"

    [[Poppler.download]]
    sha256 = "8fe5401f0883d022053cbc159e03562651d8b92d1da5c7604ae5568f1bcf0bb4"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23b3e02f37bc7e190edec34eb14e118dc4ddcb52"
os = "windows"

    [[Poppler.download]]
    sha256 = "2292640dc02baa69675b303542d06ea5a7edb1132319fb0acaac27b7f936b2b6"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v0.87.0+1/Poppler.v0.87.0.x86_64-w64-mingw32-cxx11.tar.gz"
