[[Poppler]]
arch = "aarch64"
git-tree-sha1 = "e8f372caed0f264b411f4f5b182769ee0529541e"
os = "macos"

    [[Poppler.download]]
    sha256 = "070b4dd22f3bb515d3fc61ee1d8628d93777e4a7ee65a33164e6406e52645cdf"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.aarch64-apple-darwin.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8aa3fd4493b1660f6248cb7adc0b2f0bdecaa13"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "493e4a32aaa7f4331df4b8f9994ca4bbc377e755463c09a7fa6f7cc8946a5dce"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e868ca34612ba912a088b1aaa08bdede353859f4"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "927a3e0fa43beed04693ac85ed167d72ffaf6f48198d9d94b6929f6ea8dc7a6a"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f23ba5e49632dbd727619dd26acff0e813a7c2d"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "ec9f5102ad6b4a6a24f7a5b19ec682ab046bb06303b131c2954852ee8ea37cb7"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c87e6af93f0c21e24f29ad8bbed887918ed4f7e"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "2aa7999f039ed1f97912bb0affb046d5a408e55564c301d1df57f71d64d5fd7e"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4738568a9d7489f8bdb06442b19e8afe4e4fb83b"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "21c21013bf05de4fb76f7a58faa7abde41259fe3bcedb83892f9219ae91ad654"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1204047d8ff482bcbc97b4bb69e0dbf2877aaf4"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "20da3441b656cfe6482598f1bca2efeca113ec66d997036cc813a7bc3c56c227"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Poppler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98e75c524b9b1bdfc0b9829b9cc9df3fe56dff5d"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "9322d63b2ce91e9f1e8a7bc147db6442fd34f6bfbbb84836fe554ea7b8ab1bc9"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03fb82ba329742294c4bc4b922053cf40e82ed29"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "dbf71401fa2fa04fb1476a86108a227a0cda163ecdfcc11729581e49c8f13ad5"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17908fc2c726c3150556cf5a45dfd6c1b69c92cb"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "59593fe5cf82399f29635f84736f501e45c10320e215be3036c8e25859dd5e5d"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c3a3aeffcf1355522a41e8adef7088d11829ecf"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "3ac29e2b6bd539740b83e49c61eaf20b148be3df81340398bf3ac27a2c56e22f"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d541a1c47819f473dc647ae47d38781293ff3f5"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "432dd96b59835db648a4fd82e835a6544a225dec3588345af751e92a69f957e1"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Poppler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4a308367e7a1a1ea66b655eb40d91a550d9f444"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "9e5a8df2a778e2f0d998b846486544fb272a6ba51fe8f8939d57992fa4332f01"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "623ad67ef11f23a6b976e992a5444f272edf1d1f"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "b57451197d1db88a5b5fa2437931b869dec8fd14ecbb1e4e43185f327c93ce83"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.i686-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2b90953014dc39aca16263eb3a60516b84c447d"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "5cb41ab4dbefcebf8be56791c8fd3ac34e80bf4f9455b854d5d0aead72021e6a"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.i686-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4989945311c764391e22dac873cc6749ffcef1d1"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "ce2327773d87bcfa3c3fad1060e5256124d2393bf056eb0c8c9a1473a47fa28f"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.i686-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a095c94ce5505fb986c959726bcaa2aa530a8f5"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "c95ff52edd2bdaa88dcc91041ab0b7ed2a5352afad69672a8321a4727a6c668b"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.i686-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4380fe2959b6fd7e2fc21d6dbf1b678b7fd15008"
os = "windows"

    [[Poppler.download]]
    sha256 = "dc079baaa8eab444379113b191ad8f1717d567c62dc61f529893f5e76f9ca0ae"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[Poppler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c46f4b9380ae841b1f738248fe865e11426ba9b"
os = "windows"

    [[Poppler.download]]
    sha256 = "0acc3fe38760a8c85a7dae2f85dd5a943fe32c7e9ba7ee5edbb32609de06486b"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[Poppler]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68d94dcae5f28c6a9d5e94ea47f673b5e6350ebb"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "cad0b7a24ff51a0bf19f7feffc677bf6fb627d4b97fc12de4a939c6680db30d4"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48b6cdfbf13e6a76b8bbd9abe837894e668324eb"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "3203c7ffaa932541e5ca51888b4b281f4dcd648b81bf8a4cf3e7dbdf0ab6def0"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "ad76fa3bc41ef524590561843fe59fa7f5aeac58"
os = "macos"

    [[Poppler.download]]
    sha256 = "ceff72f2f2ad153c5633afa84c7754cf9b4e80afe6467957e3ee215fb10a35ca"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-apple-darwin.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "732c0050a38cce8c97fa7bb3b768087af2a9ace2"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "5ea2bd7a450f7084e3323f0a4f7dbdb46fabde503280a7ac5debd7f90406f5d4"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ef8ccc92e31074463722e05ba34289cc2edbfc4"
libc = "glibc"
os = "linux"

    [[Poppler.download]]
    sha256 = "b818a063f8eaf3c169091c606c2be42fe7c764afc0d93c26e51eddca94b19346"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84eb787fc071d705dc03f00d127c1300d02b8977"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "3c6f03ddbd126bf52886b908ce149eae037c759c58144b6ae756a0298b3a8a29"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8448038795eeb50d4d3f56243a3c8e253bdd7cb0"
libc = "musl"
os = "linux"

    [[Poppler.download]]
    sha256 = "9e419bde8dfe8d96c293bf83fcce9e9c6a265f5d81200686c2211e6715a36b08"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[Poppler]]
arch = "x86_64"
git-tree-sha1 = "c273d5385ac9bc42d8a82a2c725cfc71c37e99a4"
os = "freebsd"

    [[Poppler.download]]
    sha256 = "096f08e05db98267069104432f99fc7e52b8dd4962337903fdc92436919de055"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-unknown-freebsd.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2178dd4d6d61fc45893f21db96455f4d061da9d"
os = "windows"

    [[Poppler.download]]
    sha256 = "2ef240a8b8a009503704408d336a3c7a24e9bd937c44c70528c8898fcce2b23e"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Poppler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f52422f26d0d2716d0e7aa02a01655199113ffa3"
os = "windows"

    [[Poppler.download]]
    sha256 = "6acfc65ca348701f37747cb92c30517d128db23db78d74a2e8dcad6368efa3f4"
    url = "https://github.com/JuliaBinaryWrappers/Poppler_jll.jl/releases/download/Poppler-v24.6.0+0/Poppler.v24.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
